# Generated by Django 4.0.3 on 2022-04-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_petphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='likes',
        ),
    ]
