# Generated by Django 4.0.3 on 2022-04-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_petphoto_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
